//BAD - outdated - buggy
(function(c,u){var a={},x=c.document.getElementsByTagName("head")[0],v,y=!1,m=[],D=!1,B=!1,z=function(a){return function(){return a}};if(!x)throw new ReferenceError('Where\'s the head? Cannot find the "head" element in the document.');a.onload=function(a){m.push(a);y&&a.call(c)};a.onload.toString=z("function onload() { [lib code] }");var i=function(){D=!0;if(!0===B&&!1===y){for(var a=0,i=m.length;a<i;a++)m[a].call(c);y=!0}};c.addEventListener?(document.addEventListener("DOMContentLoaded",i,!1),c.addEventListener("load",
i,!1)):c.attachEvent?(document.attachEvent("onDOMContentLoaded",i),c.attachEvent("onload",i)):c.onload=i;c.lib=a;v=function(){[].indexOf||(Array.prototype.indexOf=function(a){if(null==this)throw new TypeError("Array.prototype.indexOf called on null or undefined");var c=Object(this),h=c.length>>>0;if(0===h)return-1;var f=0;1<arguments.length&&(f=Number(arguments[1]),f!=f?f=0:0!=f&&(Infinity!=f&&-Infinity!=f)&&(f=(0<f||-1)*Math.floor(Math.abs(f))));if(f>=h)return-1;for(f=0<=f?f:Math.max(h-Math.abs(f),
0);f<h;f++)if(f in c&&c[f]===a)return f;return-1});Object.create||(Object.create=function(a){function c(){}if(1<arguments.length)throw Error("Object.create implementation only accepts the first parameter.");c.prototype=a;return new c});Date.now||(Date.now=function(){return(new Date).getTime()});var h,i,n,w,j;a.requested=[];h=a.requested;a.executed=[];i=a.executed;a._scriptToRequest=Object.create(null);n=a._scriptToRequest;var k;a:{try{var l=c.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMlHTTP");
l.open("GET","lib/Classes.js",!1);l.send();if(200<=l.status&&400>l.status&&!(null===l.responseText||""===l.responseText)){if(!JSON){k=(new Function("return "+l.responseText))();break a}k=JSON.parse(l.responseText);break a}}catch(v){}k=Object.create(null)}a.scriptIdToURL=k;w=a.scriptIdToURL;a._ScriptRequest=function(a,c,h){this.scriptCount=a||0;this.onload=c||function(){};this.loaded=h||0};a._ScriptRequest.toString=z("function ScriptRequest() { [lib code] }");a._ScriptRequest.prototype={scriptCount:0,
onload:function(){},loaded:0};j=a._ScriptRequest;a.require=function(){for(var a=0,l=arguments.length,k=new j(l);a<l;a++){var f=w[arguments[a]]||arguments[a];if("string"!==typeof f)throw new TypeError("Arguments needed to be a string, but found a "+typeof f);if(-1!==h.indexOf(f))-1!==i.indexOf(f)?k.loaded++:(n[f]===u&&(n[f]=[]),n[f].push(k));else{var p=document.createElement("script");p.type="text/javascript";p.src=f;x.appendChild(p);n[f]===u&&(n[f]=[]);n[f].push(k);h.push(f)}}return{onload:function(a){k.onload=
a;k.loaded===l&&a.call(c,c)}}};a.require.toString=z("function require() { [lib code] }");a.requires=a.require;a.loaded=function(a){a=w[a]||a;if(-1===i.indexOf(a)&&(i.push(a),a=n[a]))for(;a.length;)a[0].loaded++,a[0].loaded===a[0].scriptCount&&a[0].onload.call(c,c),a.splice(0,1)};a.loaded.toString=z("function loaded() { [lib code] }");a.addFileListURL=function(){};a.addFileList=function(a){for(var c in a)"string"===typeof a[c]&&(w[c]=a[c])};c.lib=a;B=!0;if(D){k=0;for(l=m.length;k<l;k++)m[k].call(c);
y=!0}};if(c.JSON)v(),a.onload(function(){var h=!!c._DEBUG;null==c.lib&&(c.lib={});var i=!1,n=/abc/.test(function(){abc})?/\b_parent\b/:/.*/,w=new TypeError("Class constructor cannot be called as a function."),j=function(a){return function(){return a}},k=function(a,c,g){return function(){var b=this._super,e;this._super=g[a];try{e=c.apply(this,arguments)}finally{this._super=b}return e}};a.Class=function(){};a.Class.prototype.toString=j("[object Class]");a.Class.toString=j("function Class() { [lib code] }");
a.Class.extend=h?function S(g,b,e){var d=this.prototype,q=b?(new Function("return function "+b+'() {\n    if ( !(this instanceof lib.Class) ) {\n        throw new TypeError("Class constructor cannot be called as a function.");\n    }\n    if ( !lib.initialising && this.init ) {\n        this.init.apply( this, arguments );\n    }\n};'))():function G(){if(!(this instanceof G))throw w;!this.initialising&&this.init&&this.init.apply(this,arguments)};q.prototype=this.prototype;a.initialising=!0;q.prototype=
new q;delete a.initialising;for(var c in g)q.prototype[c]="function"===typeof g[c]&&"function"===typeof d[c]&&n.test(g[c])?k(c,g[c],d):g[c];q.prototype.constructor=q;b&&!e&&(q.prototype.toString=j("[object "+b+"]"));q.extend=S;return q}:function g(b,a,d,c){var N=this.prototype;i=!0;d=new this;i=!1;a&&!c&&(d.toString=j("[object "+a+"]"));for(var f in b)d[f]="function"===typeof b[f]&&"function"===typeof N[f]&&n.test(b[f])?k(f,b[f],N):b[f];b=function T(){if(!(this instanceof T))throw w;!i&&this.init&&
this.init.apply(this,arguments)};b.prototype=d;b.prototype.constructor=b;b.extend=g;return b};a.Class.extend.toString=j("function extend() { [lib code] }");a.loaded&&a.loaded("lib.Class");a.Events={};var h=a.Events,l,v,m=Object.prototype.toString,y=document.createEvent,z=new TypeError('Event object missing "type" property'),f=new TypeError("Event Listener is not in the correct type"),p=Date.now;h.EventListener=a.Class.extend({handleEvent:function(){},init:function(g){this.handleEvent=g}},"EventListener");
l=h.EventListener;h.Event=a.Class.extend({timeStamp:0,type:"",target:null,cancelable:!1,defaultPrevented:!1,preventDefault:function(){this.cancelable&&(this.defaultPrevented=!0)},initEvent:function(g,b){this.type=g;this.target=b;this.timeStamp=p()}},"Event");v=h.Event;var t=Object.create(null);a.createEventType=function(g,b){t[g]=v.extend(b,g);return t[g]};a.createEventType.toString=j("function createEventType() { [lib code] }");a.createEvent=function(g){return null!=t[g]?(g=new t[g],g.timeStamp=
p(),g):y(g)};a.createEvent.toString=j("function createEvent() { [lib code] }");h.EventTarget=a.Class.extend({_listeners:{},addEventListener:function(g,b,a){var d=this._listeners[g];if(!(null!=d&&function(){for(var g="object"===typeof a?a:null,c,q=0,f=d.length;q<f;q++)if(c=this.listeners[q],c.listener.handleEvent===b&&c.scope===g)return!0;return!1}())){var c={listener:"object"===typeof b&&b.handleEvent?b:new l(b),scope:"object"===typeof a?a:null};"[object Array]"===m.call(d)?d.push(c):this._listeners[g]=
[c]}},removeEventListener:function(g,b,a){g=this._listeners[g];if("[object Array]"===m.call(g))for(var a="object"===typeof a?a:null,d=0,c=g.length;d<c;d++)if(g[d].listener.handleEvent===b&&g[d].scope===a){g.splice(d,1);break}},dispatchEvent:function(g){g.target||(g.target=this);if(!g.type)throw z;var a=0,e=this._listeners[g.type],d=e.length,c;if("[object Array]"===m.call(e))for(;a<d;a++){c=e[a].listener.handleEvent;if("function"!==typeof c)throw f;c.call(e[a].scope,g)}return g.defaultPrevented}},
"EventTarget");h.EventTarget.prototype.addEventListener.toString=j("function addEventListener() { [lib code] }");h.EventTarget.prototype.removeEventListener.toString=j("function addEventListener() { [lib code] }");h.EventTarget.prototype.dispatchEvent.toString=j("function addEventListener() { [lib code] }");h.EventTarget.prototype.on=h.EventTarget.prototype.addEventListener;a.loaded("lib.Events");for(var x=0,h=["ms","moz","webkit","o"],C=0;C<h.length&&!c.requestAnimationFrame;++C)c.requestAnimationFrame=
c[h[C]+"RequestAnimationFrame"],c.cancelAnimationFrame=c[h[C]+"CancelAnimationFrame"]||c[h[C]+"CancelRequestAnimationFrame"];c.requestAnimationFrame||(c.requestAnimationFrame=function(g){var a=p(),e=Math.max(0,16-(a-x)),d=c.setTimeout(function(){g(a+e)},e);x=a+e;return d});c.cancelAnimationFrame||(c.cancelAnimationFrame=function(g){clearTimeout(g)});var D=new TypeError("Must pass a timer as an argument to initialize TimerEvent"),H=c.clearInterval,B=c.setInterval,O=a.Class.extend({fn:function(){},
args:[],thisArg:c,sleepTime:0,init:function(g,a,e){this.method=g||function(){};this.thisArg=a||c;this.args=e||[]}},"FunctionToCall"),E=Object.create(null);E.animation=0;E.steady=1;E.as_fast_as_possible=2;a.Timer=a.Events.EventTarget.extend({ANIMATION:0,STEADY:1,AS_FAST_AS_POSSIBLE:2,TimerEvent:a.createEventType("TimerEvent",{FPS:0,targetFPS:0,delta:0,initEvent:function(g,a){if(null==a.getFPS||null==a.targetFPS||null==a.dt)throw D;this.FPS=a.getFPS();this.targetFPS=a.targetFPS;this.delta=a.dt;this._super(g,
a)}}),_clearIntervalFlag:!1,_recursionCounter:0,_tickHandlersFromMethod:Object.create(null),running:!1,paused:!1,mode:0,autoStartStop:!0,setAutoStartStop:function(a){this.autoStartStop=a},prevTime:0,dt:0,maxDelta:0.05,setMaxDelta:function(a){this.maxDelta=a},sysTimerId:-1,targetFPS:50,setFPS:function(a){this.targetFPS=a;if(this.running&&this.mode===this.STEADY){H(this.sysTimerId);var b=this;this.sysTimerId=B(function(){b.tick()},1E3/a)}},getFPS:function(){return 1/this.dt},queue:[],addToQueue:function(a,
b,e){var d=new O(a,b,e),c;this.queue.push(d);var f=function G(f){0<d.sleepTime?d.sleepTime-=f.delta:(c=a.apply(b,[f].concat(e)),"number"===typeof c&&0<c?d.sleepTime=c:!0!==c&&(this.removeEventListener("tick",G,this),this.queue.splice(this.queue.indexOf(d),1)))};null==this._tickHandlersFromMethod[a]?this._tickHandlersFromMethod[a]=[f]:this._tickHandlersFromMethod[a].push(f);this.addEventListener("tick",f,this);this.autoStartStop&&!this.running&&this.startLoop()},removeFromQueue:function(a){var b=this._tickHandlersFromMethod[a],
a=this.queue.indexOf(a);if(-1!==a){for(var e=0,d=b.length;e<d;e++)this.removeEventListener("tick",b[e],this);return this.queue.splice(a,1)}},getQueue:function(){return this.queue.slice(0)},pause:function(){this._clearIntervalFlag=this.paused=!0;this.dt=0},resume:function(){this.paused=!1;this.startLoop()},startLoop:function(){this.prevTime=p();this.running=!0;if(this.mode===this.steady){var a=this;this.sysTimerId=B(function(){a.tick()},1E3/this.targetFPS)}else this.tick()},tick:function(){if(this._clearIntervalFlag&&
-1!==this.sysTimer)H(this.sysTimerId),this.sysTimerId=-1,this._clearIntervalFlag=!1;else if(!this.paused){var g=p();this.dt=(g-this.prevTime)/1E3;this.dt>this.maxDelta&&(this.dt=this.maxDelta);if(0===this.dt&&4>this._recursionCounter)this._recursionCounter++,this.tick();else{0<this._recursionCounter&&(this._recursionCounter=0);var b=a.createEvent("TimerEvent");b.initEvent("tick",this);this.dispatchEvent(b);this.prevTime=g;g=!(this.autoStartStop&&0>=this.queue.length);if(this.mode===this.AS_FAST_AS_POSSIBLE&&
g){var e=this;setTimeout(function(){e.tick()},0)}if(this.mode===this.ANIMATION&&g){var d=this;requestAnimationFrame(function(){d.tick()})}g||(this.running=!1,this.mode===this.STEADY&&-1!==this.sysTimerId&&(H(this.sysTimerId),this.sysTimerId=-1))}}},init:function(a){this.mode="number"===typeof a?a:E[a];if(null==this.mode||0>this.mode||2<this.mode)this.mode=0}},"Timer");a.Timer.ANIMATION=0;a.Timer.STEADY=1;a.Timer.AS_FAST_AS_POSSIBLE=2;a.Timer.FunctionToCall=O;a.Timer.toString=j("function Timer() { [lib code] }");
a.Timer.prototype.tick.toString=j("function tick() { [lib code] }");a.Timer.prototype.pause.toString=j("function pause() { [lib code] }");a.Timer.prototype.resume.toString=j("function resume() { [lib code] }");a.Timer.prototype.addToQueue.toString=j("function addToQueue() { [lib code] }");a.Timer.prototype.removeFromQueue.toString=j("function removeFromQueue() { [lib code] }");a.loaded("lib.Timer");var I,J,K,A,L,s=Math.abs;a.Math={};I=a.Math.findRoot=function(a,b,e,d,c){for(var f=b,h=a(b),i=a(e),
j=h,k,l,n,r,d=d||0,c=c||1E3;0<c--;){n=e-b;s(j)<s(i)&&(b=e,e=f,f=b,h=i,i=j,j=h);k=1E-15*s(e)+d/2;l=(f-e)/2;if(s(l)<=k||0===i)return e;if(s(n)>=k&&s(h)>s(i)){var m,p;p=f-e;b===f?(m=i/h,b=p*m,r=1-m):(r=h/j,m=i/j,h=i/h,b=h*(p*r*(r-m)-(e-b)*(m-1)),r=(r-1)*(m-1)*(h-1));0<b?r=-r:b=-b;b<0.75*p*r-s(k*r)/2&&b<s(n*r/2)&&(l=b/r)}s(l)<k&&(l=0<l?k:-k);b=e;h=i;e+=l;i=a(e);if(0<i&&0<j||0>i&&0>j)f=b,j=h}};J=a.Math.translateFn=function(a,b,e){return function(d){return a(d-e)+b}};K=a.Math.inverseOf=function(a,b,e,d,
c){return function(d){return I(J(a,-d,0),b,e,c,Infinity)}};A=a.Math.integralOf=function(a,b,e){var d,c,f;return function(h){c=(h-e)/b;f=a(e);for(d=1;d<b;d+=2)f+=4*a(e+c*d);for(d=2;d<b-1;d+=2)f+=2*a(e+c*d);f+=a(h);return c*f/3}};L=a.Math.normalize=function(a,b,e,d){var c=A(a,b,e)(d);return function(b){return a(b)/c}};Math.findRoot=I;Math.translateFn=J;Math.inverseOf=K;Math.integralOf=A;Math.normalize=L;a.loaded("lib.Math");var P=Math.pow,F=Math.random,U=Array.prototype.slice;a.Probability=a.Class.extend({_value:0,
valueOf:function(){return this._value},toString:function(){return"["+100*this._value+"% Chance]"},get:function(){return this._value},set:function(a){"object"===typeof a&&a._value?this.set(a._value):"number"===typeof a&&(this._value=0<=a?1>=a?a:1:0)},increase:function(a){return new Q(1-P(1-this.value,a))},decrease:function(a){return new Q(1-P(1-this.value,-a))},test:function(){return F<this._value},init:function(a){this.set(a||0)}},"Probability");var Q=a.Probability;a.Probability.ProbDistrib=a.Class.extend({_fn:u,
_lowerLimit:u,_upperLimit:u,_samplingFn:u,setFn:function(a,b,e,d){if("function"!==typeof a)throw new TypeError("Given argument to set must be a function.");this._fn=L(a,b,e,d);this._lowerLimit=e;this._upperLimit=d;this.generateSamplingFunction()},getFn:function(){return this._fn},getRandom:function(){null==this._samplingFn&&this.generateSamplingFunction();return this._samplingFn(F())},getProb:function(a,b){return A(this._fn,a,b)},test:function(a,b){return F()<A(this._fn,a,b)},getSamplingFunction:function(){this._samplingFn||
this.generateSamplingFunction();return this._samplingFn},generateSamplingFunction:function(){this._samplingFn=K(A(this._fn,1E3,this._lowerLimit),this._lowerLimit,this._upperLimit,0.001,1E-100)},init:function(a,b,e,d){this.setFn(a,b,e,d);this.generateSamplingFunction()}},"ProbabilityDistribution");a.Probability.testList=function(a){for(var b=U.call(a),e=0;0<b.length&&F()>=b[0]/(1-e);)e+=b[0],b.shift();return a.length-b.length};a.loaded("lib.Probability");var M,R,V="toString valueOf constructor isPrototypeOf propertyIsEnumerable toLocaleString".split(" "),
h=Object.create;a.Audio={};a.Audio.AudioEvent=a.createEventType("AudioEvent",{sound:null,soundId:null,channel:null,newChannelAdded:!1,initEvent:function(a,b,e){for(var d in e)-1===V.indexOf(d)&&(this[d]=e[d]);this._super(a,b)}});M=a.Audio.Channel=a.Events.EventTarget.extend({audio:new Audio,playing:!1,play:function(g){var b=this.audio,g="number"===typeof g?g:1,e=a.createEvent("AudioEvent"),d;if(!0===this.playing){d=a.createEvent("AudioEvent");d.initEvent("beforeRestart",this,{channel:this,cancelable:!0});
if(!0===this.dispatchEvent(d))return;b.pause();b.currentTime=0}this.playing=!0;b.volume=1<g?1:0>g?0:g;e.initEvent("beforePlay",this,{channel:this,cancelable:!0});this.dispatchEvent(e)||(b.play(),d=a.createEvent("AudioEvent"),d.initEvent("restart",this,{channel:this,cancelable:!1}),e=a.createEvent("AudioEvent"),e.initEvent("play",this,{channel:this,cancelable:!1}),this.dispatchEvent(d),this.dispatchEvent(e))},init:function(g){this.audio=g.cloneNode(!0);var b=this;this.audio.addEventListener("ended",
function(){b.playing=!1;var g=a.createEvent("AudioEvent");g.initEvent("ended",b,{channel:b,cancelable:!1});b.dispatchEvent(g)})}},"Channel");R=a.Audio.Sound=a.Events.EventTarget.extend({src:"",audio:new Audio,channels:[],autoResize:!1,play:function(g){for(var b=0,e=this.channels,d=e.length,c=a.createEvent("AudioEvent"),f=!1;b<d&&e[b].playing;b++);b>=d&&(this.autoResize?(e[d]=new M(this.audio),f=!0,b=d):b=0);c.initEvent("beforePlay",this,{sound:this,channel:e[b],newChannelAdded:f,cancelable:!0});!0===
this.dispatchEvent(c)?f&&e.splice(d,1):(e[b].play(g),this.dispatchEvent(c),c=a.createEvent("AudioEvent"),c.initEvent("play",this,{sound:this,channel:e[b],newChannelAdded:f,cancelable:!1}))},init:function(a,b,c){this.audio=null!=a?new Audio(a):new Audio;this.src=null!=a?""+a:"";this.channels=[];this.autoResize=!!c;a=0;for(b="number"===typeof b?0<=b?b:0:3;a<b;a++)this.channels[a]=new M(this.audio)}});a.Audio.AudioManager=a.Events.EventTarget.extend({_sounds:[],_soundFromId:h(null),_soundFromSrc:h(null),
addSound:function(c,b,e,d){b=new R(c,b,d);d=a.createEvent("AudioEvent");d.initEvent("beforeAdd",this,{sound:b,soundId:null!=e?e:u,cancelable:!0});!0!==this.dispatchEvent(d)&&(this._sounds.push(b),this._soundFromSrc[c]=b,null!=e&&(this._soundFromId[e]=b),d=a.createEvent("AudioEvent"),d.initEvent("add",this,{sound:b,soundId:null!=e?e:u,cancelable:!0}),this.dispatchEvent(d))},removeSound:function(c){var b=this.getSound(c),e=this._sounds.indexOf(b),d=this._soundFromSrc,f=this._soundFromId,h,i=a.createEvent("AudioEvent");
i.initEvent("beforeRemove",this,{sound:b,cancelable:!0});if(!0!==this.dispatchEvent(i)){-1<e&&this._sounds.splice(e,-1);if(null!=d[c]&&b===d[c])delete d[c];else if(""!==b.src&&b===d[b.src])delete d[b.src];else for(h in d)if(b===d[h]){delete d[h];break}if(null!=f[c]&&b===f[c])delete f[c];else for(h in f)if(b===f[h]){delete f[h];break}i=a.createEvent("AudioEvent");i.initEvent("remove",this,{sound:b,cancelable:!1});this.dispatchEvent(i)}},getSound:function(a){if(null!=this._soundFromSrc[a])return this._soundFromSrc[a];
if(null!=this._soundFromId[a])return this._soundFromId[a]},playSound:function(c,b){var e=a.createEvent("AudioEvent"),d=this.getSound(c);e.initEvent("beforePlay",this,{sound:d,cancelable:!0});!0!==this.dispatchEvent(e)&&(this.getSound(c).play(b),e=a.createEvent("AudioEvent"),e.initEvent("play",this,{sound:d,cancelable:!1}),this.dispatchEvent(e))}});a.loaded("lib.Audio")});else{i=document.createElement("script");i.type="text/javascript";i.src="http://cdnjs.cloudflare.com/ajax/libs/json3/3.2.4/json3.min.js";
var t=!1;i.onreadystatechange=function(){if(("loaded"===this.readyState||"complete"===this.readyState)&&!t)t=!0,v()};i.onload=function(){t||(t=!0,v())};x.appendChild(i)}})(window);

